config/routes.rb
Rails.application.routes.draw do
  resource :user do
    get :activate
  end
  resource :session, only: %i[new create destroy]
  resource :password_reset, only: %i[new create edit update]
  get "protected" => "home#protected"
  root "home#index"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: {minimum: 8}, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true

  before_update :setup_activation, if: -> { email_changed? }
  after_update :send_activation_needed_email!, if: -> { previous_changes["email"].present? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Sorcery::Controller

  before_action :require_active, if: -> { current_user }

  def not_authenticated
    redirect_to(new_session_path, alert: "Please login")
  end

  def require_active
    if current_user.activation_state != "active"
      logout
      redirect_to(:new_session, alert: "please activate!")
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_login, only: %i[protected]

  def index
  end

  def protected
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])

    @user.deliver_reset_password_instructions! if @user

    redirect_to(new_session_path, :notice => "Instructions have been sent to your email.")
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
    end
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end

    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.change_password(params[:user][:password])
      redirect_to(new_session_path, :notice => "Password was successfully updated.")
    else
      render :edit
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_login, only: %i[destroy]

  def new
  end

  def create
    @user = login(params[:email], params[:password], params[:remember])
    if @user
      redirect_back_or_to(:new_user, notice: "Login successfully")
    else
      flash.now[:alert] = "Login failed"
      render :new
    end
  end

  def destroy
    logout
    redirect_to(:new_session, notice: "Logged out!")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: %i[new create activate]
  before_action :set_user, only: %i[show edit update destroy]

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path, notice: "Created!"
    else
      flash.now[:alert] = "Create failed"
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to edit_user_path, notice: "Updated!"
    else
      flash.now[:alert] = "Update failed"
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to new_session_path, notice: "Destroyed!"
  end

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      redirect_to(new_session_path, :notice => "User was successfully activated.")
    else
      not_authenticated
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>home/index</h1>

app/views/home/protected.html.erb
<h1>home/protected</h1>
<p>This page can only be viewed by logged-in users</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SorceryAuthRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Protected", protected_path %></li>
      <% if current_user %>
        <li><%= link_to "Show", user_path %></li>
        <li><%= link_to "Edit", edit_user_path %></li>
        <li><%= link_to "Logout", session_path, method: :delete %></li>
        <li><%= link_to "Destroy", user_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Register", new_user_path %></li>
        <li><%= link_to "Login", new_session_path %></li>
      <% end %>
    </ul>

    <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>

<%= form_for @user, url: password_reset_path(@token) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag :id, @token %>

  <div class="field">
    <%= f.label :email %>
    <%= @user.email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot Password?</h1>

<%= form_with(url: password_reset_path, method: :post, local: true) do |form| %>
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
    <%= form.submit "Reset my password!" %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, url: user_path) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit</h1>

<%= render "form", user: @user %>

app/views/users/new.html.erb
<h1>Register</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<h1>Show</h1>

<table>
  <thead>
    <tr>
      <th>email</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @user.email %></td>
    </tr>
  </tbody>
</table>